
services:
  db:
    image: svnelv/webeng_db
    restart: always
    hostname: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: webeng
  app:
    build:
      context: .
    restart: always
    ports:
      - "1234:80"