
services:
  db:
    image: mysql:5.6
    restart: always
    hostname: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: webeng
    volumes:
      - ./webeng.sql:/docker-entrypoint-initdb.d/1.sql
  app:
    build:
      context: .
    restart: always
    ports:
      - "1234:80"